<div class="mega-home-content">
<div class="row">
<div class="col-md-4 col-lg-4">
<ul>
<li><a title="Face" href="{{store url='face-products-men'}}">Face</a>
<ul class="nav-submenu">
<li><a title="Face Wash" href="{{store url='face-wash'}}">Face Wash</a></li>
<li><a title="Face Scrub" href="{{store url='face-scrub'}}">Face Scrub</a></li>
<li><a title="Face Moisturizer" href="{{store url='face-moisturizer'}}">Face Moisturizer</a></li>
<li><a title="Anti-Aging" href="{{store url='anti-aging'}}">Anti-Aging</a></li>
</ul>
</li>
<li><a title="Body" href="{{store url='body-products-men'}}">Body</a>
<ul class="nav-submenu">
<li><a title="Body Wash" href="{{store url='body-wash'}}">Body Wash</a></li>
<li><a title="Body Bar/Soap" href="{{store url='body-bar-soap'}}">Body Bar/Soap</a></li>
<li><a title="Deodorant" href="{{store url='deodorant'}}">Deodorant</a></li>
<li><a title="Solid Colognes" href="{{store url='solid-colognes'}}">Solid Colognes</a></li>
</ul>
</li>
</ul>
</div>
<div class="col-md-8 col-lg-8 hide-mobile">
<div class="row">
<div class="col-md-12">
<h3 class="feature-title"><?php echo __('Our recommendations'); ?></h3>
<div class="our-recommendations-slider">
<div class="slide-items">
<div class="our-recommendations-image"><img src="http://217.23.12.152/~moquerm2/pub/media/wysiwyg/categories/blumaan_original_styling_meraki1.jpg"></div>
<h4 class="product-name"><a href="#">Original by Blumaan Styling Meraki 74 ml. </a></h4>
<div class="our-recommendations-price">€ 19,95</div>
</div>
<div class="slide-items">
<div class="our-recommendations-image"><img src="http://217.23.12.152/~moquerm2/pub/media/wysiwyg/categories/blumaan_original_styling_meraki1.jpg"></div>
<h4 class="product-name"><a href="#">Original by Blumaan Styling Meraki 74 ml. </a></h4>
<div class="our-recommendations-price">€ 19,95</div>
</div>
<div class="slide-items">
<div class="our-recommendations-image"><img src="http://217.23.12.152/~moquerm2/pub/media/wysiwyg/categories/blumaan_original_styling_meraki1.jpg"></div>
<h4 class="product-name"><a href="#">Original by Blumaan Styling Meraki 74 ml. </a></h4>
<div class="our-recommendations-price">€ 19,95</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>