<?php
/**
 * Copyright Â© 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<form class="form custom-shipping"
      id="custom-shipping-form"
      >
    <div class="shiping-form-control">
        <fieldset class="fieldset">
            <div class="field country">
                <label class="label" for="country"><span><?php /* @escapeNotVerified */ echo __('Country:') ?></span></label>
                <div class="control">
                    <select name="country_id" id="country" class="validate-select number" title="Country">
                        <option value="">-- Please Select --</option>
                        <?php echo $block->getCountries() ?>
                    </select>
                </div>
            </div>
            <div class="field number">
                <label class="label" for="number"><span><?php /* @escapeNotVerified */ echo __('Number of Sunglasses:') ?></span></label>
                <div class="control">
                    <select name="number" id="number" class="validate-select number" title="Number of Sunglasses">
                        <option value="">-- Please Select --</option>
                        <?php echo $block->getNumbers() ?>
                    </select>
                </div>
            </div>
            <div class="field cost">
                <label class="label" for="shipping"><span><?php /* @escapeNotVerified */ echo __('Shipping cost:') ?></span></label>
                <div class="control">
                    <strong><span class="price">€ </span></strong>
                    <strong><span class="wait_loader" id="loader1" style="display: none;"><?php echo __('Please wait...'); ?></span></strong>
                </div>
            </div>

            <div class="field eta2">
                <label class="label" for="eta"><span><?php /* @escapeNotVerified */ echo __('Delivery time in business days:') ?></span></label>
                <div class="control">
                    <strong><span class="eta"></span></strong>
                    <strong><span class="wait_loader" id="loader2" style="display: none;"><?php echo __('Please wait...'); ?></span></strong>
                </div>
            </div>
        </fieldset>
    </div>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Calculate') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Calculate') ?></span>
            </button>
        </div>
    </div>
</form>
<script type="text/javascript">
    require(["jquery"], function ($) {
        $(document).ready(function () {
            $(document).on('click', '.submit', function () {
                event.preventDefault();
                $('.price').hide();
                $('.eta').hide();
                $('.wait_loader').show();
                var customurl = "<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>";
                var country = $('#country :selected').val();
                var number = $('#number :selected').val();
                $.ajax({
                    url: customurl,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        country_id: country,
                        number: number,
                    },
                    complete: function (response) {
                        data = response.responseJSON;
                        //console.log(data);
                        $('.price').html('€' + data.price);
                        if (data.eta) {
                            $('.eta').html(data.eta + " day(s)");
                        }else{
                           $('.eta').html(data.eta); 
                        }
                        $('.wait_loader').hide();
                        $('.price').show();
                        $('.eta').show();
                    },
                    error: function (xhr, status, errorThrown) {
                        console.log('Error happens. Try again.');
                    }
                });
            });
        });
    });
</script>
