<?php

/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_ShopbyBrand
 */
?>
<?php
/** @var \Amasty\ShopbyBrand\Block\Widget\BrandList $block */
$items = $block->getIndex();
$columns = abs((int) $block->getData('columns'));
$brandLetters = $block->getAllLetters();
$isShowCount = $block->getData('show_count');
$isShowImages = $block->getData('show_images');
$imgWidth = $block->getImageWidth();
$imgHeight = $block->getImageHeight();
$isShowSearch = $block->getData('show_search');
$isShowFilter = $block->getData('show_filter');
$filterDisplayAll = $block->getData('filter_display_all');
$display_zero = $block->getData('display_zero');
$width = floor(100 / $columns);
?>
<style>
    .bare-list .ambrands-image {
        max-width: <?= $block->escapeHtml($imgWidth); ?>px;
        max-height: <?= $block->escapeHtml($imgHeight); ?>px;
    }

    .brand-item .am-image-wrapper {
        height: <?= $block->escapeHtml($imgWidth); ?>px;
    }

    .brand-item {
        max-width: <?= $block->escapeHtml($imgWidth); ?>px;
        min-width: <?= $block->escapeHtml($imgWidth); ?>px;
        min-height: <?= $block->escapeHtml($imgWidth + 30); ?>px;
    }

    .brand-item .no-img {
        width: <?= $block->escapeHtml($imgWidth); ?>px;
        line-height: <?= $block->escapeHtml($imgWidth); ?>px;
        font-size: <?= $block->escapeHtml($imgWidth * 0.65); ?>px;
    }

    #maincontent .brand-images li.brand-item {
        list-style-type: none;
        text-align: center;
        border: 1px solid #ccc;
        margin-right: 7.5px;
        margin-bottom: 15px;
        width: calc(20% - 15px);
        margin-left: 7.5px;
        padding: 15px;
        margin-top: 0 !important;
    }

    .brand-item .am-image-wrapper {
        height: 90px;
        display: flex;
        align-items: center;
    }

    .bare-list .ambrands-image {
        max-width: 90%;
        max-height: 90px;
    }

    #maincontent .brand-images li.brand-item p {
        text-align: center;
        height: 90px;
        font-size: 18px !important;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .brand-item .no-img {
        width: auto;
        line-height: initial;
        font-size: 55px;
    }

    .brands-filters {
        padding: 0 7.5px;
    }

    .brands-filters .letter {
        padding: 4px 10px;
    }

    .brands-filters a.letter.-letter-all {
        margin-right: 10px;
    }

    @media (min-width: 768px) {
        .brand-images .brands-letter {
            width: <?= $block->escapeHtml($width) ?>%;
        }
    }
</style>

<div class="content">
    <?php if ($items) : ?>
        <?php if ($isShowSearch || $isShowFilter) : ?>
            <div class="brands-filters">
                <?= $block->getSearchHtml(); ?>
                <?php if ($isShowFilter) : ?>
                    <div class="letters">
                        <div class="letters-box">
                            <a href="javascript:void(0)" class="letter -letter-all" data-ambrands-js="filter-letter" title="<?= $block->escapeHtml(__('All Brands')) ?>">
                                <?= $block->escapeHtml(__('All Brands')) ?>
                            </a>
                        </div>
                        <div class="letters-box">
                            <?php if ($filterDisplayAll) : ?>
                                <?php foreach (array_merge(range('A', 'Z'), ['#']) as $letter) : ?>
                                    <a href="javascript:void(0)" data-ambrands-js="filter-letter" class="letter <?= (!(in_array($letter, $brandLetters)))
                                                                                                                                        ? '-disabled'
                                                                                                                                        : 'letter-' . $block->escapeHtml($letter) ?>">
                                        <?= $block->escapeHtml($letter) ?></a>
                                <?php endforeach; ?>
                            <?php else : ?>
                                <?php foreach ($brandLetters as $letter) : ?>
                                    <a href="javascript:void(0)" data-ambrands-js="filter-letter" class="letter letter-<?= $block->escapeHtml($letter) ?>">
                                        <?= $block->escapeHtml($letter) ?>
                                    </a>
                                <?php endforeach;  ?>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>
        <div class="brand-images">
            <ul class="bare-list">
                <?php foreach ($items as $letters) : ?>

                    <?php foreach ($letters as $letter => $options) : ?>
                        <?php foreach ($options as $option) : ?>
                            <li class="brand-item" <?=
                                                                        /** @noEscape */
                                                                        $block->getTooltipAttribute($option) ?>>
                                <a href="<?= $block->escapeUrl($option['url']) ?>" class="item" title="<?= $block->escapeHtml($option['label']) ?>">
                                    <?php if ($option['img'] && $isShowImages) : ?>
                                        <div class="am-image-wrapper">
                                            <img class="ambrands-image" src="<?= $block->escapeUrl($option['img']) ?>" title="<?= $block->escapeHtml($option['alt']) ?>" alt="<?= $block->escapeHtml($option['alt']) ?>" />
                                        </div>
                                    <?php else : ?>
                                        <p class="label"><?= $block->escapeHtml($option['label']) ?></p>
                                    <?php endif ?>
                                </a>
                            </li>
                        <?php endforeach ?>
                    <?php endforeach ?>
                <?php endforeach ?>
            </ul>
        </div>
        <div style="clear:both;"></div>
    <?php else : ?>
        <?= $block->escapeHtml(
                __(
                    'Please select brand attribute in Stores -> Configuration -> Amasty Extensions -> Improved Layered Navigation:
                    Brands.'
                )
            ) ?>
    <?php endif ?>
</div>

<script>
    require([
        'jquery',
        'Amasty_ShopbyBrand/js/brand-filter',
        'domReady!'
    ], function($) {
        $('[data-ambrands-js="filter-letter"]').on('click', function(e) {
            e.preventDefault();
            $(this).applyBrandFilter('[data-ambrands-js="brand-letter"]');
        });
    });

    <?php if ($block->isTooltipEnabled()) : ?>
        require([
            'jquery',
            "mage/tooltip"
        ], function($) {
            $('[data-amshopby-js="brand-tooltip"]').tooltip({
                position: {
                    my: "left-20 bottom",
                    at: "right top",
                    collision: "flip flip",
                    using: function(position, feedback) {
                        $(this).css(position);
                        $("<div>")
                            .addClass("arrow")
                            .addClass(feedback.vertical)
                            .addClass(feedback.horizontal)
                            .appendTo(this);
                    }
                },
                tooltipClass: "amshopby-brand-tooltip",
                content: function() {
                    var current = $(this).is('li') ? $(this) : $(this).parent();
                    return current.data('tooltip-content');
                }
            });
        });
    <?php endif ?>
</script>